# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano@2
    shield: xavien_left nice_view
  - board: nice_nano@2
    shield: xavien_right nice_view
  - board: nice_nano@2
    shield: xavien_dongle
  - board: xiao_ble
    shield: xavien_dongle_xiao
  - board: nice_nano@2
    shield: xavien_left_master nice_view
  - board: nice_nano@2
    shield: xavien_right_master nice_view
  - board: nice_nano@2
    shield: settings_reset
  - board: xiao_ble
    shield: settings_reset

