CONFIG_ZMK_POINTING=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y



CONFIG_ZMK_SLEEP=n
CONFIG_PM_DEVICE=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_EXT_POWER=y


CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_ZMK_LOG_LEVEL_DBG=y

# Keep USB logging usable
CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
CONFIG_NRFX_USBD_LOG_LEVEL_ERR=y