manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zmkfirmware
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: urob
      url-base: https://github.com/urob
    - name: duanexavierbondad
      url-base: https://github.com/duanexavierbondad
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: m165437
      url-base: https://github.com/M165437
    - name: yyevax
      url-base: https://github.com/yyevax
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: nice-view-image
      remote: yyevax
      revision: main
  self:
    path: config
