CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=8
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=50
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=9

CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y

# For split keyboards:
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y


### ZMK STUDIO
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
